name: test and linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client-set-up-and-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node@14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
        working-directory: ./client
      - run: npm test
        working-directory: ./client
      - run: npm run lint
        working-directory: ./client

  server-set-up-and-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node@14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
        working-directory: ./server
      - run: npm test
        working-directory: ./server
      - run: npm run lint
        working-directory: ./server